# Generated by Django 2.2.12 on 2020-10-31 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='电影名称')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.TextField(verbose_name='短评内容')),
                ('star', models.IntegerField(max_length=1, verbose_name='星级')),
                ('comment_time', models.DateField(verbose_name='短评时间')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.Film')),
            ],
        ),
    ]
